# Generated by Django 5.2.7 on 2025-10-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=100)),
                ('yoshi', models.IntegerField()),
                ('kursi', models.IntegerField()),
                ('guruhi', models.CharField(max_length=20)),
                ('universiteti', models.CharField(max_length=150)),
            ],
        ),
    ]
